name: 'Telegram Action'
description: "Send sth. to telegram with Github Action"
author: 'SettingDust'
inputs:
  chatId:
    required: true
    description: 'Get with @userinfobot'
  botToken:
    required: true
    description: 'Get with @BotFather'
  content:
    required: false
    description: 'Message content'
  medias:
    required: false
    description: 'Media urls or paths. Split with \n'
  type:
    required: false
    description: 'document, photo, video'
    default: document
  format:
    required: false
    description: 'Markdown, MarkdownV2, HTML'
    default: 'MarkdownV2'
  disableWebPagePreview:
    required: false
    description: 'Disables link preview'
    default: 'false'
  disableNotification:
    required: false
    description: 'Disables notification'
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
